run-duct:
  image: golang:1.26-alpine
  cache:
    key: duct
    paths: [.duct/]
  before_script:
    - apk add --no-cache git
  script:
    - "[ -d .duct ] || git clone --branch main --depth 1 https://gitlab.com/nmvinicius/duct.git .duct"
    - "sh .duct/bin/duct run"