definitions:
  caches:
    duct: .duct

pipelines:
  default:
    - step:
        name: Duct
        image: atlassian/default-image:latest
        caches:
          - duct
        script:
          - "[ -d .duct ] || git clone --branch stable --depth 1 https://bitbucket.org/nmvinicius/duct.git .duct"
          - "sh .duct/bin/duct run"