name: Duct

on:
  push:
    branches: [main, stable]
  pull_request:
    branches: [main]

jobs:
  duct:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Duct
        run: |
          # Clona duct stable ou usa cache
          [ -d .duct ] || git clone --branch stable --depth 1 https://github.com/nmvinicius/duct.git .duct
          sh .duct/bin/duct run